# -*- coding: utf-8 -*-
"""text_to_image_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OEdmnlRHGdbbKHbWcYHYBRp8WG_L8HNA
"""

!pip install diffusers transformers accelerate --upgrade
!pip install safetensors

import torch
from diffusers import StableDiffusionPipeline
import matplotlib.pyplot as plt

from huggingface_hub import login
login("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")

from diffusers import StableDiffusionPipeline
pipe=StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16,
    use_safetensors=True
)
pipe=pipe.to("cuda")

user_prompt=input("enter your image prompt:")

image=pipe(user_prompt).images[0]
plt.imshow(image)
plt.axis("off")
plt.title("Generated image")
plt.show()

!pip freeze > requirements.txt

from google.colab import files
files.download('requirements.txt')

